#!/bin/sh

curl --user akankshachandre:Indore_2312 -s http://localhost:8080/job/devopsmil2/build?token=12345

sleep 30
BUILD_JSON=$(wget --auth-no-challenge --http-user=akankshachandre --http-password=Indore_2312 -qO- http://127.0.0.1:8080/job/devopsmil2/lastBuild/api/json)
RESULT=$(echo $BUILD_JSON | grep -oe '"result":"\w\+"' | cut -d \" -f4 | tr -d '\n')

echo $RESULT

if [ $RESULT = "FAILURE" ]; then
    echo "Reset to previous commit"
    previous=$(git log --skip=1 --max-count=1 --pretty=format:"%H")
    git reset $previous
fi
