#!/bin/sh

curl --user ashintr:amruta123 -s http://localhost:8080/job/job2/build?token=12345

sleep 30
JSON=$(wget --auth-no-challenge --http-user=ashintr --http-password=amruta123 -qO- http://127.0.0.1:8080/job/job2/lastBuild/api/json)
RESULT=$(echo $JSON | grep -oe '"result":"\w\+"' | cut -d \" -f4 | tr -d '\n')

echo $RESULT

if [ $RESULT = "FAILURE" ]; then
    echo "Reset to previous commit"
    previous=$(git log --skip=1 --max-count=1 --pretty=format:"%H")
    git reset $previous
fi
